---
env:
  browser: true
  builtin: true
  es6: true
  jquery: true
  node: true
globals:
  window: true
  DataTable: true
  document: true
  Foundation: true
  jQuery: true
  lodash: true
  Modernizr: readonly
  wp: readonly
  tinymce: readonly
  _wpUtilSettings: readonly
plugins:
  - import
  - jsdoc
extends:
  - 'plugin:@wordpress/eslint-plugin/custom'
  - 'plugin:@wordpress/eslint-plugin/es5'
  - 'plugin:@wordpress/eslint-plugin/esnext'
  - 'plugin:@wordpress/eslint-plugin/i18n'
  - 'plugin:@wordpress/eslint-plugin/jsdoc'
parser: '@babel/eslint-parser'
parserOptions:
  babelOptions:
    babelrc: true
  ecmaFeatures:
    modules: true
    impliedStrict: true
  ecmaVersion: 2020
  requireConfigFile: false
  sourceType: module
rules:
  array-bracket-spacing: 0
  block-scoped-var: error
  camelcase: error
  comma-dangle:
    - error
    - arrays: only-multiline
      objects: only-multiline
      imports: only-multiline
      exports: only-multiline
      functions: never
  comma-style:
    - error
    - last
  computed-property-spacing: 0
  dot-notation:
    - error
    - allowKeywords: false
  eqeqeq:
    - error
    - allow-null
  guard-for-in: error
  indent:
    - error
    - 2
    - SwitchCase: 1
      VariableDeclarator: first
  jsdoc/check-types:
    - error
    - exemptTagContexts:
      - tag: param
        types: true
      - tag: return
        types: true
  jsdoc/tag-lines:
    - warn
    - any
    - endLines: null
      tags:
        param:
          lines: any
  new-cap: 0
  no-bitwise: error
  no-caller: error
  no-cond-assign:
    - error
    - except-parens
  no-console: 0
  no-debugger: error
  no-empty: error
  no-eval: error
  no-extend-native:
    - error
    - exceptions:
      - Date
  no-extra-parens: 0
  no-irregular-whitespace: error
  no-iterator: error
  no-loop-func: error
  no-mixed-operators: warn
  no-mixed-spaces-and-tabs:
    - error
    - smart-tabs
  no-multi-spaces:
    - error
    - exceptions:
        ImportDeclaration: true
        VariableDeclarator: true
  no-multi-str: error
  no-new: error
  no-nested-ternary: 0
  no-plusplus: 0
  no-proto: error
  no-restricted-syntax:
    - error
    - selector: CallExpression[callee.object.name='console'][callee.property.name!=/^(log|warn|error|info|trace)$/]
      message: Unexpected property on console object was called
  no-script-url: error
  no-sequences: error
  no-shadow: warn
  no-undef: error
  no-unused-vars: warn
  no-with: error
  object-shorthand:
    - error
    - consistent
  quotes: 0
  semi:
    - 0
    - never
  space-in-parens: 0
  strict:
    - warn
    - global
  valid-typeof: error
  wrap-iife:
    - error
    - inside
settings:
  import/resolver:
    alias:
      map:
        - - '@'
          - ./src/js
  jsdoc:
    ignorePrivate: true
    preferredTypes:
      Array: array
      boolean: bool
    tagNamePreference:
      virtual: abstract
      extends: augments
      tag constructor: class
      const: constant
      defaultvalue: default
      desc: description
      host: external
      fileoverview: file
      overview: file
      emits: fires
      func: function
      method: function
      var: member
      arg: param
      argument: param
      prop: property
      returns: return
      exception: throws
root: true
