---
extends: '@wordpress/scripts/config/.stylelintrc.json'
cache: true
cacheLocation: /tmp/.stylelintcache
ignorePath: ./.stylelintignore
overrides:
  - files:
      - '*.scss'
      - '**/*.scss'
    customSyntax: postcss-scss
rules:
  at-rule-empty-line-before: null
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - apply
        - at-root
        - each
        - else
        - extend
        - for
        - function
        - if
        - include
        - layer
        - mixin
        - return
        - tailwind
  comment-whitespace-inside: always
  declaration-empty-line-before: null
  font-family-name-quotes: always-where-recommended
  no-descending-specificity: null
  no-invalid-double-slash-comments: true
  rule-empty-line-before:
    - always-multi-line
    - except:
        - after-single-line-comment
        - first-nested
  scss/no-global-function-names: null
  selector-attribute-quotes: always
  unit-allowed-list:
    - px
    - em
    - rem
    - vw
    - vh
    - deg
    - '%'
    - s
    - dpi
    - pt
    - fr
  # Deprecated
  indentation:
    - 2
    - baseIndentLevel: auto
      except:
        - value
      ignore:
        - value
      indentInsideParens: once-at-root-twice-in-block
  max-line-length: null
  string-quotes: single
