---
extends: '@wordpress/scripts/config/.stylelintrc.json'
cache: true
cacheLocation: /tmp/.stylelintcache
ignorePath: ./.stylelintignore
plugins:
  - stylelint-scss
rules:
  at-rule-empty-line-before: null
  declaration-empty-line-before: null
  indentation:
    - 4
  max-empty-lines:
    - 5
  max-line-length:
    - 120
    - ignore: non-comments
      ignorePattern:
        - /(https?\://[0-9,a-z]*.*)|(^description\\:.+)|(^tags\\:.+)/i
  no-descending-specificity:
    - true
    - ignore:
        - selectors-within-list
  no-invalid-double-slash-comments: true
  rule-empty-line-before:
    - always-multi-line
    - except:
        - after-single-line-comment
        - first-nested
  scss/at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - apply
        - extend
        - layer
        - tailwind
  scss/at-mixin-parentheses-space-before: never
  string-quotes: single
  unit-allowed-list:
    - px
    - em
    - rem
    - vw
    - vh
    - deg
    - '%'
    - s
    - dpi
    - pt
    - fr
