---
extends: '@wordpress/scripts/config/.stylelintrc.json'
cache: true
cacheLocation: /tmp/.stylelintcache
ignorePath: ./.stylelintignore
plugins:
  - stylelint-scss
  - stylelint-stylistic
rules:
  at-rule-empty-line-before: null
  declaration-empty-line-before: null
  stylistic/indentation: tab
  stylistic/string-quotes: single
  stylistic/max-empty-lines: 5
  stylistic/max-line-length:
    - 120
    - ignore: non-comments
      ignorePattern:
        - /(https?\://[0-9,a-z]*.*)|(^description\\:.+)|(^tags\\:.+)/i
  no-descending-specificity:
    - true
    - ignore:
        - selectors-within-list
  no-invalid-double-slash-comments: true
  rule-empty-line-before:
    - always-multi-line
    - except:
        - after-single-line-comment
        - first-nested
  scss/at-rule-no-unknown:
    - true
    - ignoreAtRules:
        - apply
        - extend
        - function
        - include
        - layer
        - mixin
        - tailwind
  scss/at-mixin-parentheses-space-before: never
  scss/comment-no-empty: null
  scss/no-global-function-names: null
  unit-allowed-list:
    - px
    - em
    - rem
    - vw
    - vh
    - deg
    - '%'
    - s
    - dpi
    - pt
    - fr
