---
# Change to your project's root directory (i.e. the name of the folder that contains ALL wordpress files).
PROJECT:
  &hostname "stats"

# Accepts 'development' or 'production'.
STATUS: "development"

# Set to true if you want static asset revisioning; helpful for cache busting.
REVISIONING: true

# Browsersync config.
BROWSERSYNC:
  url:
    - "http://"
    - *hostname
    - ".test"
  # Files for BrowserSync to watch.
  watch:
    - "**/*.scss"
    - "**/*.js"
    - "**/*.php"

# Autoprefixer will make sure your CSS works with these browsers.
COMPATIBILITY:
  - "last 2 versions"
  - "> 1%"
  - "ios >= 9"

# Grunt will reference these paths when it copies files.
PATHS:
  # Path to admin directory.
  admin: "admin"
  # Path to dist folders.
  dist: "dist"
  # Paths to static assets that aren't images, CSS, or JavaScript.
  assets:
    - "src/**"
    - "node_modules/multiselect/{css,img,js}/**"
    - "node_modules/yadcf/jquery.dataTables.yadcf.*"
    - "vendor/mobiledetect/mobiledetectlib/Mobile_Detect.php"
    - "vendor/sinergi/browser-detector/src/*"
    - "!src/{img,js,sass}/**"
  # Paths to the main image directory.
  images:
    - "src/img/**"
    - "!src/img/{competitions,players,programs,timeline,unions,venues}/**"
  # Paths to the main JavaScript directory.
  js:
    - "src/js/**/*"
  # Paths to Sass libraries, which can then be loaded with @import.
  sass:
    - "node_modules/foundation-sites/scss"
  # Paths to Sass templates.
  templates:
    - "src/sass/*.scss"
  # Entries of main files.
  entries:
    - "src/js/rdb.js"
    - "src/js/rdb-admin.js"
  # Paths for the package task to include/exclude in .zip archive.
  package:
    - "**/*"
    - "**/WR/match/{mens,womens}-{eagles,sevens}/**"
    - "**/WR/wr-utilities.php"
    - "!**/.babelrc"
    - "!**/.editorconfig"
    - "!**/.eslint*"
    - "!**/.git*"
    - "!**/.stylelint*"
    - "!**/node_modules/**"
    - "!**/packaged/**"
    - "!**/src/**"
    - "!**/phpcs.xml.dist"
    - "!**/composer.json"
    - "!**/composer.lock"
    - "!**/config.yml"
    - "!**/config-default.yml"
    - "!**/gulpfile.babel.js"
    - "!**/package.json"
    - "!**/package-lock.json"
    - "!**/*.sublime-*"
    - "!**/webpack.config.js"
    - "!**/WR/**"
  # Paths for PHP CodeSniffer.
  phpcs:
    - "**/*.php"
    - "!wpcs"
    - "!wpcs/**"
